### ISSUE TITLE
Cannot install latest version (v4.3.11) in an Nx 14.x workspace

### ISSUE THREAD

**Issue by dgonzalezr** [bikecoders/ngx-deploy-npm#469]
Cannot update to v4.3.11 from v4.3.10 in an NX workspace still in v.14x

![CleanShot 2023-01-27 at 19 24 38](https://user-images.githubusercontent.com/328492/215154229-027db8fb-3dd6-4dcb-9653-bf9bfa53a835.png)

It seems that the latest version requires Nx v15.

**Comment by dianjuar** [comment]
The fix should be on [ngx-deploy-npm@5.0.0](https://www.npmjs.com/package/ngx-deploy-npm/v/5.0.0)

Feel free to reopen the issue if the problem persists.

**Comment by dianjuar** [comment]
Thank you @samuelfernandez
Marvelous contribution #473.

**Comment by dianjuar** [comment]
Deeply analyzing the problem, it is not solved.

If you are on nx v14, you will still have the problem due to unresolved peer dependencies. 

As #473 indicates,
> Regarding opening for v14, I'd propose to treat that in a separate PR, alongside the e2e tests to ensure compatibility.

---

I'll suggest two actions:
- Migrate to Nx 15 and use ngx-deploy-npm v5
- Stick with some ngx-deploy-npm prior version were Nx14 was supported. V4.3.3 is a good candidate.
- Wait until we officially support nx v14.

On ngx-deploy-npm, we want to offer the broader support we can offer.

**Comment by dgonzalezr** [comment]
I'm using v4.3.10 with NX v14.8.6 without issues. Also v4.3.5 was the one that fixes the issue where large files couldn't be published to NPM.

**Comment by dianjuar** [comment]
react-native integration tests are failing. I will fix them and then release 5.1.0 to offer support to nx14

**Comment by dianjuar** [comment]
You should be able to update to [ngx-deploy-npm@5.1.0](https://www.npmjs.com/package/ngx-deploy-npm/v/5.1.0) without problems.

On 5.1.0, we offer support to Nx14
