### ISSUE TITLE
Impossible to init ngx-deploy-npm in non-Angular NX monorepo

### ISSUE THREAD

**Issue by leandrocrs** [bikecoders/ngx-deploy-npm#65]
When we try to init **ngx-deploy-npm** inside a non-Angular [NX](https://nx.dev) monorepo, I'm facing the following issue:

```
yarn  nx generate ngx-deploy-npm:init                                
yarn run v1.22.10
$ nx generate ngx-deploy-npm:init
Cannot find module '@angular-devkit/core'
Require stack:
- /Users/contoso/Projects/nx_react_monorepo/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/contoso/Projects/nx_react_monorepo/node_modules/@nrwl/tao/src/commands/generate.js
- /Users/contoso/Projects/nx_react_monorepo/node_modules/@nrwl/tao/index.js
- /Users/contoso/Projects/nx_react_monorepo/node_modules/@nrwl/cli/lib/init-local.js
- /Users/contoso/Projects/nx_react_monorepo/node_modules/@nrwl/cli/bin/nx.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If ngx-deploy-npm is just a npm wrapper, why is it bounded to `@angular-devkit/core`?

**Comment by dianjuar** [comment]
Thank you for opening an Issue.

You shouldn't be facing this, by `nx generate ngx-deploy-npm:init` it should install all the peer-dendencies for you.  This should be the expected behavior, see [here](https://github.com/nrwl/nx/issues/4523#issuecomment-760964206).

I'll be working to solve this.

---

As a quick solution for this problem, you can install all the peer-deps by hand and you should free to go.
```bash
 npm install -D @angular-devkit/architect @angular-devkit/core @angular-devkit/schematics
```

Here you have an explanation of why: 

This is a [CLI Builder](https://angular.io/guide/cli-builder) adapted to work on Nx workspaces. The packages that you mention are [peer dependencies](https://nodejs.org/es/blog/npm/peer-dependencies/), packages that this builder needs in order to work. You can verify this [here](https://github.com/bikecoders/ngx-deploy-npm/blob/master/src/package.json#L75-L77) and when you install the tool

![image](https://user-images.githubusercontent.com/7026066/124402424-084fc880-dce5-11eb-82c8-538b35244d8c.png)

But again, you should be seeing this, I'll be working to solve this ASAP

**Comment by dianjuar** [comment]
Issue #72 created to address this problem
